import { useModelStore } from '../../stores/modelStore';
import { FEATURE_LABELS } from '../../types';

export function PredictTab() {
  const { model, trainingStatus } = useModelStore();

  const hasTrainedModel = model !== null && trainingStatus === 'complete';

  return (
    <div className="p-8">
      {/* Status Banner */}
      {!hasTrainedModel ? (
        <div className="bg-warm-light border border-warm/30 rounded-xl p-6 mb-8 flex items-center gap-4">
          <span className="text-3xl">⚠️</span>
          <div>
            <h3 className="text-lg font-semibold text-warm">No Trained Model Available</h3>
            <p className="text-gray-600">
              Please train a model in the "Train Model" tab first to make predictions.
            </p>
          </div>
        </div>
      ) : (
        <div className="bg-green-50 border border-green-200 rounded-xl p-6 mb-8 flex items-center gap-4">
          <span className="text-3xl">✅</span>
          <div>
            <h3 className="text-lg font-semibold text-green-700">Model Ready</h3>
            <p className="text-gray-600">
              Your neural network is trained and ready to make predictions.
            </p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Input Features */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h3 className="text-xl font-semibold text-gray-800 mb-6 flex items-center gap-2">
            <span className="text-2xl">📥</span>
            Input Features
          </h3>
          <div className="space-y-5">
            {Object.entries(FEATURE_LABELS)
              .filter(([key]) => key !== 'soundPressureLevel')
              .map(([key, label]) => (
                <div key={key}>
                  <label className="block text-base font-medium text-gray-700 mb-2">
                    {label}
                  </label>
                  <input
                    type="number"
                    disabled={!hasTrainedModel}
                    className="w-full px-4 py-3 text-lg border-2 border-gray-200 rounded-lg
                             focus:ring-2 focus:ring-accent focus:border-accent
                             disabled:bg-gray-100 disabled:cursor-not-allowed
                             transition-colors"
                    placeholder="Enter value..."
                  />
                </div>
              ))}
          </div>

          <button
            disabled={!hasTrainedModel}
            className="w-full mt-8 py-4 bg-accent text-white text-lg font-semibold rounded-lg
                     hover:bg-accent/90 disabled:bg-gray-300 disabled:cursor-not-allowed
                     transition-colors shadow-lg shadow-accent/20"
          >
            🎯 Predict Sound Level
          </button>
        </div>

        {/* Prediction Result */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h3 className="text-xl font-semibold text-gray-800 mb-6 flex items-center gap-2">
            <span className="text-2xl">📤</span>
            Prediction Result
          </h3>

          <div className="h-64 bg-gray-50 rounded-lg flex flex-col items-center justify-center border-2 border-dashed border-gray-200">
            <span className="text-5xl mb-4 opacity-50">🔊</span>
            <p className="text-gray-400 text-lg text-center">
              Predicted sound pressure level<br />will appear here
            </p>
          </div>

          <div className="mt-6 p-4 bg-primary-light rounded-lg">
            <h4 className="font-semibold text-gray-800 mb-2">About the Target</h4>
            <p className="text-gray-600 text-base">
              The model predicts the <strong>Scaled Sound Pressure Level</strong> (in decibels),
              which measures the self-noise generated by the airfoil during wind tunnel tests.
            </p>
          </div>
        </div>
      </div>

      <p className="text-gray-400 mt-8 text-center text-base">
        Full prediction interface with airfoil visualization will be implemented in WP10-WP11.
      </p>
    </div>
  );
}
